### ISSUE TITLE
GitHub Pages

### ISSUE THREAD

**Issue by JustusAdam** [Feliix42/felixwittwer.de#1]
Ich sehe du hast deine Seite in reinem HTML gebaut und auf Uberspace gehostet. Vielleicht könnte dich dann auch [das hier](https://pages.github.com) interessieren. 

Da kannst du kostenfrei statische Weisheiten auf GitHub hosten, über ein GitHub repository. (so ist zum Beispiel auch [meine Webseite](http://justus.science) gehostet. ([repo](http://github.com/JustusAdam/justusadam.github.io))

**Comment by Feliix42** [comment]
Danke für den Tipp! :)
Ich hatte GitHub Pages schon mal gesehen aber eben nicht wirklich ausprobiert. Ich werde mich daran mal versuchen!

**Comment by JustusAdam** [comment]
Das coolste daran ist eigentlich die integration über githubs page build system [Jekyll](http://jekyllrb.com). Da kann man seine Webseite dynamisch aus Markdown Quelldateien zusammensetzen lassen. Da brauch man sich nicht so viel mit HTML herumzuschlagen.
